/**
 * pendingSubmissionsStore.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Lightweight cross-tab localStorage store that tracks suggestions currently
 * in the process of being submitted (the 1–5 second window between the user
 * clicking "Submit" and the API call completing).
 *
 * Why this exists
 * ───────────────
 * If two employees on the same device (different browser tabs) or the same
 * local network simultaneously click Submit with nearly identical ideas, the
 * duplicate check on each side will find the other's in-flight entry BEFORE
 * either reaches the database. This catches the concurrent-submission gap that
 * a plain DB check cannot cover.
 *
 * How it works
 * ────────────
 * 1. Before running the duplicate scan, each submission registers itself here.
 * 2. The scan reads all active (non-expired, non-self) entries and checks them.
 * 3. After the API call resolves (success or failure), the entry is removed.
 * 4. Entries auto-expire after EXPIRY_MS to handle page crashes / force-close.
 * 5. A BroadcastChannel fires on every write so other tabs get the update
 *    immediately (no polling needed).
 *
 * Storage key : "flowboost_pending_subs"
 * Channel name: "flowboost_pending_bc"
 */

const STORE_KEY = "flowboost_pending_subs";
const EXPIRY_MS = 10 * 60 * 1000; // 10 minutes — safety valve for crashes
const BC_NAME   = "flowboost_pending_bc";

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface PendingEntry {
  /** Unique temporary ID generated by createPendingId() */
  id: string;
  employeeNo?: string;
  employeeName?: string;
  /** Epoch ms when entry was registered — used for expiry */
  registeredAt: number;
  /** Text fields extracted from the form (for similarity check) */
  subject?: string;
  presentMethod?: string;
  proposedMethod?: string;
  benefits?: string;
  category?: string;
  suggestionType?: string;
}

// ─── Internal helpers ──────────────────────────────────────────────────────────

function genId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  // Fallback for environments without crypto.randomUUID
  return `${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
}

function readStore(): PendingEntry[] {
  try {
    const raw = localStorage.getItem(STORE_KEY);
    if (!raw) return [];
    const all: PendingEntry[] = JSON.parse(raw);
    // Drop expired entries on every read
    return all.filter(e => Date.now() - e.registeredAt < EXPIRY_MS);
  } catch {
    return [];
  }
}

function writeStore(entries: PendingEntry[]): void {
  try {
    localStorage.setItem(STORE_KEY, JSON.stringify(entries));
    // Notify other tabs so they re-read immediately
    try {
      const bc = new BroadcastChannel(BC_NAME);
      bc.postMessage({ type: "updated", ts: Date.now() });
      bc.close();
    } catch {
      /* BroadcastChannel not supported in all environments — single-tab graceful degradation */
    }
  } catch {
    /* Private browsing mode or storage quota exceeded — silently degrade */
  }
}

// ─── Public API ────────────────────────────────────────────────────────────────

/**
 * Generate a new unique ID for a pending submission.
 * Call once per handleSubmit invocation and store in a ref.
 */
export function createPendingId(): string {
  return genId();
}

/**
 * Register a submission as "in progress".
 * Must be called BEFORE running the duplicate scan so that other
 * concurrent submitters can see it.
 */
export function registerPending(entry: PendingEntry): void {
  // Ensure registeredAt is fresh on (re-)registration
  const entries = readStore().filter(e => e.id !== entry.id);
  entries.push({ ...entry, registeredAt: Date.now() });
  writeStore(entries);
}

/**
 * Remove a submission from the pending store.
 * Call AFTER the API call returns (whether success or failure),
 * or when the user cancels.
 */
export function unregisterPending(id: string): void {
  writeStore(readStore().filter(e => e.id !== id));
}

/**
 * Return all active pending entries, excluding the given id (your own).
 * Other tabs' submissions will appear here within milliseconds of registration.
 */
export function getActivePending(excludeId?: string): PendingEntry[] {
  return readStore().filter(e => e.id !== excludeId);
}

/**
 * Prune all expired entries.
 * Useful to call once on app startup to keep localStorage clean.
 */
export function clearExpiredPending(): void {
  // readStore() already filters expired entries; just re-writing cleans up
  writeStore(readStore());
}

/**
 * Subscribe to changes made by other tabs.
 * Returns an unsubscribe function.
 *
 * Usage:
 *   const unsub = subscribeToPendingChanges(() => refresh());
 *   // later:
 *   unsub();
 */
export function subscribeToPendingChanges(cb: () => void): () => void {
  try {
    const bc = new BroadcastChannel(BC_NAME);
    const handler = () => cb();
    bc.addEventListener("message", handler);
    return () => {
      bc.removeEventListener("message", handler);
      bc.close();
    };
  } catch {
    // BroadcastChannel not available — return no-op unsubscribe
    return () => {};
  }
}
